### ISSUE TITLE
ngxTextHighlight is not working in angular7

### ISSUE THREAD

**Issue by sai-chaitanya-viswanadhuni** [mraghuram3/ngx-text-highlight#1]
ngxTextHighlight is not working. Please provide the complete reference of usage

**Comment by mraghuram3** [comment]
Can you be more specific, what caused the issue or what error you got while you were using the package?
The package is working fine with angular 7, kindly find the below example for the reference.
**Include the CSS provided in your index.html or create a CSS class as shown below as per your requirement**
https://stackblitz.com/edit/angular-qqpum7?embed=1&file=src/app/app.component.html

**Comment by sai-chaitanya-viswanadhuni** [comment]
I need to search the string in whole html page that contains many div. How can i do it?

**Comment by mraghuram3** [comment]
every div which is required to be searched should have ngxTextHighlight directive

**Comment by sai-chaitanya-viswanadhuni** [comment]
Is there any other possibility without using the ngxTextHighlight directive in all divs? I have very large data. It is difficult to store all the data in a string in TS file file. Can u please help me out with different solution?

**Comment by mraghuram3** [comment]
It requires the directive to be rewritten to search through all the child elements and highlight the text, the current one doesn't support this.

**Comment by AltRoot17** [comment]
> ngxTextHighlight is not working. Please provide the complete reference of usage

I had a same issue , Do you have any solutions?
